FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./bun.lockb ./bun.lockb

COPY ./packages ./packages

COPY ./turbo.json ./turbo.json
COPY ./apps/http-server ./apps/http-server

RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]